# suppa.py generateEvents -i /home/AD.UNLV.EDU/Shared_Data/AlternativeSplicing/syn52065646_LongRead/jaquino_analysis/NanoporeRNASeq_extended_annotations.gtf -o /home/AD.UNLV.EDU/Shared_Data/AlternativeSplicing/syn52065646_LongRead/jaquino_analysis/suppa_bambu_gtf/FC_events -f ioe -e SE MX SS RI FL
# for event in SE RI MX AL AF A5 A3
# do
#     suppa.py psiPerEvent \
#         --ioe-file /home/AD.UNLV.EDU/Shared_Data/AlternativeSplicing/syn52065646_LongRead/jaquino_analysis/suppa_bambu_gtf/FC_events_${event}_strict.ioe \
#         --expression-file /home/AD.UNLV.EDU/Shared_Data/AlternativeSplicing/syn52065646_LongRead/jaquino_analysis/bambu_tx_tpm.txt \
#         -o /home/AD.UNLV.EDU/Shared_Data/AlternativeSplicing/syn52065646_LongRead/jaquino_analysis/suppa_bambu_gtf/psi_${event}
# done


# using the original gtf, instead of the one generated by bambu, to see if there are any differences in the events generated
suppa.py generateEvents -i /home/AD.UNLV.EDU/Shared_Data/AlternativeSplicing/syn52065646_LongRead/reproducing_nextflow_pipeline/Homo_sapiens.GRCh38.107_ERCC.gtf -o /home/AD.UNLV.EDU/Shared_Data/AlternativeSplicing/syn52065646_LongRead/jaquino_analysis/suppa_original_gtf/FC_events -f ioe -e SE MX SS RI FL
for event in SE RI MX AL AF A5 A3
do
    suppa.py psiPerEvent \
        --ioe-file /home/AD.UNLV.EDU/Shared_Data/AlternativeSplicing/syn52065646_LongRead/jaquino_analysis/suppa_original_gtf/FC_events_${event}_strict.ioe \
        --expression-file /home/AD.UNLV.EDU/Shared_Data/AlternativeSplicing/syn52065646_LongRead/jaquino_analysis/bambu_tx_tpm.txt \
        -o /home/AD.UNLV.EDU/Shared_Data/AlternativeSplicing/syn52065646_LongRead/jaquino_analysis/suppa_original_gtf/psi_${event}
done